version: 2
updates:
  # Monitor npm dependencies (Node.js project)
  - package-ecosystem: "npm"
    directory: "/"        # location of package.json
    schedule:
      interval: "weekly"  # can be daily, weekly, or monthly
      day: "monday"       # optional (for weekly schedule)
      time: "04:00"       # UTC time to run
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - your-github-username   # replace with your GitHub username
    labels:
      - "dependencies"
      - "auto-update"

  # Monitor GitHub Actions themselves
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
